letras = list('Stark bank')

print(letras[1:4])
print(letras[1:9])
print(letras[1:9:2])
print(letras[0:9:2])
print(letras[:9:2])
print(letras[:-1:2])
print(letras[::2])
print(letras[::-1])
letras.reverse()
print(letras)

# print(list(range(10)))
print('sopapos'[::-1])
print('roma me tem amor'[::-1])
